### ISSUE TITLE
Wemos D1 mini pro CP2104 not able to flash s0tool

### ISSUE THREAD

**Issue by MPJK77** [huizebruin/s0tool#101]
Not able to flash s0tool to my wemos D1 mini pro CP2104.
I can flash everything else on the wemos (e.g. WLED, Tasmota etc.)
I am not able to flash s0tool via the browser or via Home Assistant.
Is there any other way to flash s0tool?

**Comment by huizebruin** [comment]
Fixed it with the new release.

**Comment by huizebruin** [comment]
i made one special for the wemos D1 mini pro.
check the flash page under specials.
[https://huizebruin.github.io/s0tool/](https://huizebruin.github.io/s0tool/)

**Comment by MPJK77** [comment]
Dag Wobbe, ik heb de special net geprobeert echter deze werkt helaas ook
niet. Said heeft hem ook geprobeert en ook hij krijgt hem niet geflashed.

Groeten Maarten (MPJK77)

Op zo 22 jan. 2023 18:57 schreef Wobbe ***@***.***>:

**Comment by vincenttor** [comment]
ik denk dat ik hier ook tegen aan loop, wat ik ook doe hij pakt hem niet.
Zal is met een ouder model chip proberen of deze wel gaat, wilde al een bericht sturen met een scherm opname dat er weinig tot niks gebeurd.

**Comment by prvakt** [comment]
Having same issue with D1 mini pro CP2104 - flashing is stucked on "preparing installation" screen. Any chance this can be fixed?

**Comment by huizebruin** [comment]
At this moment I can't find wy it is not working. When I look at the code I see the right device but it won't install for no reason.

**Comment by huizebruin** [comment]
it wil only work on a wemos d1 mini v1 /V3 and v4.
the others will not work.
