### ISSUE TITLE
It looks like there is an issue with the calculation of the total water amount

### ISSUE THREAD

**Issue by MPJK77** [huizebruin/s0tool#108]
Hi,

It looks like the calculation of the total amount is wrong. (After updating ESPhome in HA a few days ago)
My usage would be extreme today wich is not the case.
Maybe there is an issue with dots and commas? (look at the different notation between pulserate and usage)
![image](https://user-images.githubusercontent.com/35330802/216147411-f0099ef7-ed7e-43d6-ab52-5658d76c85bc.png)
![image](https://user-images.githubusercontent.com/35330802/216144682-0dc11060-2cc5-4dfe-9402-97c6ef7a9a44.png)
![image](https://user-images.githubusercontent.com/35330802/216145336-d7384afa-ff60-4968-92de-231ce720c448.png)

Also if you compare the increasing of "Stand" and "Totaal" it does not equally add up.

Regards, Maarten

**Comment by HobbitBluelabel** [comment]
Did you add the watermeter to the energy dashboard?
Then your usage is totally wrong. I have the same problem. If i remove it
from the energy dashboard, everything is fine .

Op wo 1 feb. 2023 21:08 schreef MPJK77 ***@***.***>:

**Comment by MPJK77** [comment]
I did remove the watermeter from the energy dashboard yesterday. And reset and restarted the device with no luck.
There is realy something wrong with the conversions I think.
![image](https://user-images.githubusercontent.com/35330802/216311733-0b73bb02-ad2b-4269-b88f-7f7c54709a9a.png)

This whas all set to zero yesterday at 22.10 p.m.
![image](https://user-images.githubusercontent.com/35330802/216312045-5874c149-f30f-41c1-8775-1bf0da85ade4.png)

**Comment by MPJK77** [comment]
I did update the divice and reset all sensors.
How do u explain a usage of 136990 m3 of water in 1 day?
And look at the peak of 5000 m3 this morning at 06.00 am how is that possible?

**Comment by huizebruin** [comment]
i think that the npn sensor stands on the metal for a couple of time , and than counting on the numbers.
that's the only thin i can tink of.

**Comment by So871** [comment]
MK , stel eens niet zo'n moeilijke vragen.....


But , There seemed to be a similar issue in esphome version 2022.10.0 .

@huizebruin you could try to test this with the fix issued in issue 3730.
 https://github.com/esphome/issues/issues/3730
