### ISSUE TITLE
And how can i install the config on a board: nodemcuv2 ?

### ISSUE THREAD

**Issue by maartentmm** [huizebruin/s0tool#110]
please provide complete yaml

**Comment by maartentmm** [comment]
And how can i install the config on a board: nodemcuv2 ?

**Comment by So871** [comment]
The complete YAML consist of the 3 included files.

Esphome/watermeter.yaml
Esphome/components/basis.yaml
Esphome/components/watermeter.yaml

Put those 3 together and you're set.
