### ISSUE TITLE
how to assign static IP address to s0tool

### ISSUE THREAD

**Issue by AppleFlapp** [huizebruin/s0tool#119]
Hi, a noob here just starting with esp home.

I want to give the s0tool a static ip address but where can i do that?
I followed the installation guide but I was not able to change the IP address anywhere.

Thanks for your help.

PS. It can be done in Dutch but in English might reach more people.

Edit:
You will always see... searching your ass off and as soon as you have posted the question you find the answer.

Fixed.

**Comment by huizebruin** [comment]
Did you put it under the code after you flashed it by the GitHub page?

**Comment by AppleFlapp** [comment]
Yes I did. I just edited the YAML file via ESP home by adding a few lines.  Last five lines in the code below.

`wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
    # Optional manual IP
  manual_ip:
    static_ip: !secret static_ip_s0tool
    gateway: !secret gateway
    subnet: !secret subnet`

I did also add the line to set power save mode to none because I had connection losses every couple of minutes.
Still not convinced this is working properly now.

And we are getting at another issue now, I would like to get rid off the integrated webserver too
because it is not very friendly for the ESP8266 board according the ESP home website.
But it looks like I can't use the download option via the Github page then because another yaml file needs to be modified for that.

> Please note that enabling this component will take up a lot of memory and can lead to problems, especially on the ESP8266.

**Comment by huizebruin** [comment]
> And we are getting at another issue now, I would like to get rid off the integrated webserver too
> because it is not very friendly for the ESP8266 board according the ESP home website.
> But it looks like I can't use the download option via the Github page then because another yaml file needs to be modified for that.

I'm using it for over a year and never had any problems with it.

**Comment by HobbitBluelabel** [comment]
Same here....
Noticed no problems with the webinterface. Running stable for months.

Hartelijke groet,
Jan-Willem van den Hoek

Op vr 7 apr. 2023 17:27 schreef Wobbe ***@***.***>:
