### ISSUE TITLE
Support for esp01_1m or esp32dev 

### ISSUE THREAD

**Issue by BDV77** [huizebruin/s0tool#125]
Hi,

At this moment I have a own build working setup which I made some years ago and wanted to upgrade to the S0Tool code/interface so I have all the nice sensors and stuff. 

But the current hardware is a ESP8266 with board type: esp01_1m.
Alternatively I have esp32 modules available with board type esp32dev.

How can I get the S0tool code running on one of these devices?
I only need the watermeter only configuration.

Thanks in advance,

**Comment by huizebruin** [comment]
The board is a wemos d1 v1 / v3 /v4
because this one still handles the 5v from the npn most esp32 cant handel 5v on there input
