### ISSUE TITLE
Use internal pull-up/down resistors

### ISSUE THREAD

**Issue by vincentwolsink** [huizebruin/s0tool#127]
Thanks for the great work. I am wondering, instead of using external pull-up/down resistors, wouldn't it be an option to use the esp internal ones?

**Comment by vincentwolsink** [comment]
I now see that the NPN sensor needs 5v to function. I am using a Cyble sensor which works fine with internal pull-up.
Would be nice if we could get a config with pull-up enabled.

**Comment by huizebruin** [comment]
Yes I can make a version with the internal resistor.

I will make it this week.

**Comment by huizebruin** [comment]
Made a update to 2023.10.33 with this option on it. 
Look at the special version.

**Comment by vincentwolsink** [comment]
Thanks, works! 🚀
