### ISSUE TITLE
How to update

### ISSUE THREAD

**Issue by cyberfilou** [huizebruin/s0tool#135]
hello 

I have versie v23.09.32. and a want to update to V23.04.30
how should I do this without losing the existing data
THANKS
I use Home assistant last Version, and only S0Tools for water ( D2 )

Cyberfilou

**Comment by huizebruin** [comment]
I'm working on it how te do the update.
on paper and when its done i will put it online

**Comment by huizebruin** [comment]
![image](https://github.com/huizebruin/s0tool/assets/62996429/d6454e85-4830-4c88-ab27-822a80ea07a3)

Go to your ESPHome dashboard .
1. click on the 3 dots by the S0tool.
2. click on validate , so its getting the new code from GitHub.
3. click on install and wait until its finish.

Now you should have the latest version on it.
