### ISSUE TITLE
changing port and board

### ISSUE THREAD

**Issue by alexswart** [huizebruin/s0tool#136]
Hello,

i want to flash my nodemcuv2 with a watermeter connected to port D6
but i cant change the board and port nr
i have forked the github and give it a try but he want still connect to your github

**Comment by huizebruin** [comment]
There are multi links to the re-pro.
That how its getting the updates.
Its better to choose a wemos d1 mini and then it will work easy.
It uses the ports couple of times in the code.
if only needed for the watermeter, i posted a older version on my website, that can you make it your own but it not getting updated.
[https://www.huizebruin.nl/home-assistant/esphome/watermeter-uitlezen-in-home-assistant-met-esphome/](https://www.huizebruin.nl/home-assistant/esphome/watermeter-uitlezen-in-home-assistant-met-esphome/)
