### ISSUE TITLE
Meterstand werkt niet bij

### ISSUE THREAD

**Issue by cschillings** [huizebruin/s0tool#171]
Ik heb de meterstand via de service aangepast naar wat op de meter staat, hij telt wel de sensor die bij reboot terug naar 0 gaat maar die meterstand telt niet op.
Geen idee wat ik fout doe, heb hem pas geupdate en ervoor werkte dit altijd goed.
Ik heb de Itron watermeter.
![IMG_0607](https://github.com/huizebruin/s0tool/assets/60855190/5a4de96d-aaa7-4602-93b9-db8460100f84)

**Comment by huizebruin** [comment]
Hmm dit probleem is hier nog niet bekend, ik ga dit ook even vragen binnen mijn NL discord groep.
Wees daar ook welkom als je wilt. https://discord.gg/n6p2e3DG

Ik ga dit ook onderzoeken.

**Comment by cschillings** [comment]
Pulsrate is op een of andere manier veranderd, daarom klopte de berekening natuurlijk niet meer. Kan gesloten worden!

**Comment by huizebruin** [comment]
Mooi dat je het probleem hebt gevonden en op kunnen lossen, had nog even navraag gedaan op mijn discord groep daar hebben een aantal het ook geprobeerd en daar waren geen problemen.
