### ISSUE TITLE
Problemen with update 

### ISSUE THREAD

**Issue by huizebruin** [huizebruin/s0tool#180]
Problem with 2 times the platform ESPhome in the code.

I will try to fix it tonight.

![image-36.png](https://github.com/huizebruin/s0tool/assets/62996429/1ad67136-61c1-4560-bf77-0f38132718bd)

@schmm  thanks for the testing.

**Comment by Hurr1c4n3** [comment]
Also got a problem with the last update but it seems different:
![image](https://github.com/huizebruin/s0tool/assets/845516/8d5d384d-ee99-4130-b103-58e3d283cad3)


```
INFO ESPHome 2024.6.3
INFO Reading configuration /config/esphome/s0tool-watermeter-c03608.yaml...
INFO Updating https://github.com/huizebruin/s0tool/@main
INFO Detected timezone 'Europe/Amsterdam'
Failed config

update.http_request: [source /data/packages/b59da29a/esphome/components/s0tool-watermeter-update.yml:2]
  
  Component update.http_request requires 'platform: http_request' in component 'ota'.
  platform: http_request
  name: Firmware Update
  source: https://s0tool.nl/s0tool-watermeter-manifest.json
```

**Comment by Hurr1c4n3** [comment]
After flashing the esp from the s0tool website and after that through the esphome on Home Assistant it works again.

**Comment by huizebruin** [comment]
Should be fixed in https://github.com/esphome/issues/issues/5980 ESPHome version 2024.6.4 and above

**Comment by huizebruin** [comment]
> After flashing the esp from the s0tool website and after that through the esphome on Home Assistant it works again.

Good to here it is working again.
