### ISSUE TITLE
When using s0tool/esphome/watermeter.yaml it reports every pulse as 3.6L instead of 1.0L

### ISSUE THREAD

**Issue by compacthack** [huizebruin/s0tool#19]
Hello, I'm using your code for measuring water usage and it works great, and it works well with the update interval as 1s instead of default 60s, but it reports every pulse from sensor as 3.6L instead of 1.0L
I'm sure its a function of reducing the update interval to 1s, I played with the code and when it is set to count pulses over 60s & removed the filter it reports correctly, but you only get updates every minute and the update lag is annoying. 
Maybe if the reported value is just divided by 3.6 then it should report the pulse as 1L. 
I was also thinking of trying the esphome pulse count - rising_edge option, and triggering as the water meters spinning flag 1st triggers the sensor, as the flag may come around and trigger the sensor but stops there and won't record 1L usage until the flag as passed and the pulse finishes ?
Thanks for all your work.

**Comment by huizebruin** [comment]
Would you like to try this one out for me?

https://github.com/huizebruin/s0tool/blob/dev/esphome/pulscounter.yaml

I made some changes.

Wobbe

**Comment by compacthack** [comment]
Hi Wobbe, nice work. That is working great now. Will test over a couple of Days. Thanks for your hard work

**Comment by compacthack** [comment]
I may have spoken to soon, the id: "sensor_pulse_meter_total" is showing 1L correctly every pulse, but "id: watermeter_total" goes up by 6L every pulse. Another question and this might be more of a HA question but is there anyway to manually change the "id: watermeter_total" reading so it starts counting from a particular number, then it would be calibrated with the real reading from the physical water meter? thanks again. 

![screen-1](https://user-images.githubusercontent.com/19682513/163705674-04bce641-afaa-4408-9193-034e6e092a1a.jpeg)
 
![screen-2](https://user-images.githubusercontent.com/19682513/163705682-76875841-b885-4f65-8b22-fa67619bb16d.jpeg)

**Comment by huizebruin** [comment]
How is it now ?
