### ISSUE TITLE
Unable to flash S0tool water meter to WeMos D1 mini V4.0

### ISSUE THREAD

**Issue by Xelaph** [huizebruin/s0tool#211]
I am unable to flash the water meter to my WeMos D1 mini V4.0.
It gives a timeout error and the only option is back, which sends it into an infinite connecting message.
The installation of the S0tool Standard *does* work, so it's not a problem with my setup.

Would I be able to use the Standard without using the kWh meter?

**Comment by huizebruin** [comment]
Hello @Xelaph ,

i mostly use the wemos d1 mini version 1
that one works most of the thime very good.

Yes you can install the standard version of the s0tool and use only the water counter, of the s0 side.

Did you install the right drivers for that board?
can you post a screenshot about the error?

Wobbe

**Comment by Xelaph** [comment]
I bought the v4 because it is linked on your website to OpenCircuit.
The right drivers are installed.

These are screenshots of the error and the following unending connection loop.
![image](https://github.com/user-attachments/assets/b915132f-c29b-48bf-8b1a-3906634e1658)
![image](https://github.com/user-attachments/assets/939664b7-3ae2-48ca-bbb5-93011fe13b35)

**Comment by huizebruin** [comment]
Hello @Xelaph 

did you push the button on the side and then connect the wemos to your pc or laptop?
and pushing it antul you here a sound that ist connected.

and than click on the install button.

**Comment by Xelaph** [comment]
That all works, because I am able to install the Standard version. It's just the water meter version that does not work.

**Comment by Xelaph** [comment]
Ik zit ook nog te kijken naar het aansluiten van de npn sensor. Ik heb onderstaande layout en die op jouw website is net anders. Ik zie dat blauw op de ground moet, maar waar moeten bruin en zwart?
![image](https://github.com/user-attachments/assets/04f9e4de-f149-411a-b5e3-26c5373ef56a)

**Comment by huizebruin** [comment]
> Ik zit ook nog te kijken naar het aansluiten van de npn sensor. Ik heb onderstaande layout en die op jouw website is net anders. Ik zie dat blauw op de ground moet, maar waar moeten bruin en zwart? ![image](https://private-user-images.githubusercontent.com/70099710/353963804-04f9e4de-f149-411a-b5e3-26c5373ef56a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NTM1MTcsIm5iZiI6MTcyMjQ1MzIxNywicGF0aCI6Ii83MDA5OTcxMC8zNTM5NjM4MDQtMDRmOWU0ZGUtZjE0OS00MTFhLWI1ZTMtMjZjNTM3M2VmNTZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDE5MTMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxM2E1NWFjYjViMjcyNWY5ZjVkMWYxN2QzZDBmNzk4MDk3MjNmYzliZDRhM2Q2NzFkM2ZiYjQ0YWY0MzYzNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JIeMGiNk-FD1srxkIf6mNG7g4PL_qc154G1hMpAyjqQ)

![image](https://github.com/user-attachments/assets/082e5b70-ac35-47e6-adc4-c56c48034fcd)
Ik gebruik de v1 omdat die de 5v pen heeft, misschien dat de 3,3v ook werkt maar dat weet ik niet 100% zeker dat hier niet getest.

daarom gebruik ik de v1.
Wees ook welkom op mijn nederlandstalige discord groep over de s0tool / ha en 3d print en veel meer. https://discord.gg/zEMDnd4P

**Comment by Xelaph** [comment]
Dan moet je even kijken naar de link die je op je website hebt staan. Ik zie nu dat je linkt naar: https://opencircuit.nl/Product/WeMos-D1-mini-V3.1-Wifi-Module?affiliate=1VL4KIAMBZ&cid=github maar als je daar op klikt kom je uit bij https://opencircuit.nl/product/wemos-d1-mini-v4.0-wifi-module en die heb ik gehaald ervan uitgaande dat het zou werken :facepalm:

**Comment by huizebruin** [comment]
ik ga dat deel aanpassen, 
de v4 is dus 3,3v en daar weet ik niet zeker of dat gaat werken.
en de link is omgezet door hun , dan gaat die link weg naar opencircuit.

**Comment by Xelaph** [comment]
Ik heb hem uiteindelijk op dezelfde manier aangesloten en dat werkt!
Ik heb nog eventjes verder gekeken, maar zover ik kan zien zijn alle esp8266 3.3V. Bijvoorbeeld ook degene die je op amazon list die er net zo uit ziet als die van jouw foto's. Ze hebben wel een 5V uitgang, dat is bij die van mij de VBUS, maar de internen werken allemaal op 3.3V. Zie ook de website van wemos voor de [v4](https://www.wemos.cc/en/latest/d1/d1_mini.html) en [v3](https://www.wemos.cc/en/latest/d1/d1_mini_3.1.0.html) waar ook staat dat alle GPIO pinnen op 3.3V werken

**Comment by Xelaph** [comment]
Het enige waar ik dus mee zit is dat de water meter versie dus niet wil installeren, maar de standaard wel

**Comment by huizebruin** [comment]
> Het enige waar ik dus mee zit is dat de water meter versie dus niet wil installeren, maar de standaard wel

Ik ga morgen even die beide codes vergelijken. Misschien dat er iets niet juist staat. Ik houd je op de hoogte daarvan.
