### ISSUE TITLE
Version not visible

### ISSUE THREAD

**Issue by JGeeforce** [huizebruin/s0tool#223]
I did a clean build files and a new install, and then the version information is gone...

![image](https://github.com/user-attachments/assets/a49088a1-1dd7-4ed7-941d-04a094a2e35e)

Also not shown in the web interface. 
3.6.1 is shown in the details from the device.

**Comment by huizebruin** [comment]
I will look at it as soon as possible.

**Comment by huizebruin** [comment]
I found it,  i will fix it tomorrow. 

Thanks for the feedback.

**Comment by JGeeforce** [comment]
Thanks for your fast response and action.

**Comment by huizebruin** [comment]
schould be fixed [#270](https://github.com/huizebruin/s0tool/actions/runs/10297704195)

**Comment by JGeeforce** [comment]
Yea it has been fixed, thanks.
