### ISSUE TITLE
stream pointer vanished  / http_request error

### ISSUE THREAD

**Issue by bert1111** [huizebruin/s0tool#234]
**Describe the bug*
I had some wifi issues (broken antenna) which were resolved but suddenly the s0 meter vanished from my network.
I installed the latest update through the website with a usb cable.
I can set the network and then after a few seconds I see stream pointer vanished. And device connection is lost again.
I did find that there is a bug somewhere with esp home but not yet solved. Is there a workaround? Strange thing is that it has worked for two months before the wifi problem.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by huizebruin** [comment]
Do you see a ssid with the name ```S0tool***``` with your mobile?
Than its not connected to your wifi network.

And than you must connect it again to your network.
you can connect to the s0tool ssid.
and go to ```192.168.4.1``` and there you can connect to your wifi network again.

**Comment by bert1111** [comment]
no that ssid doesn't appear anymore. it has something to do with this issue. https://github.com/esphome/issues/issues/5949. I don't know if you're aware of this.

**Comment by huizebruin** [comment]
What i heart it was fixed an little time ago. But it doesn't when i see this.
i will contact some of my other Dutch users on my discord if they also have the same error after the update or flashing the s0tool.

What version of Home assistant and ESPHome are you using?

**Comment by bert1111** [comment]
Firmware: 3.6.2 (ESPHome 2024.9.1)
Versie | core-2024.9.3
Installation type | Home Assistant OS
What does appear to work is not finish the flashing by skipping the search for wifi networks.
Than the s0tool network appears. Go to the url you mentioned above.
Set the wifi there. The watermeter is now connected for a few minutes were it previously disconnected after a few seconds with mentioned error.

**Comment by bert1111** [comment]
Nope. It's gone again. Same error [http_request.arduino:137]
Stream pointer vanished!

**Comment by huizebruin** [comment]
When u use the same esp it stores the ssid and password in his esp.
That's why you don't see the selecting ssid (wifi) list.

**Comment by bert1111** [comment]
I think I'm not explaining it good enough. Or I don't understand it enough.
I'll try again but be clearer of the steps I'm taking.

So the watersensor was working fine up until last night with version 3.6.1.
Today I saw in HA that all watermeter sensors were not available.
I reinstalled via the webpage to version 3.6.2.
And from the moment I select my wifi network I lose connection with error http_request.arduino:137]
Stream pointer vanished!

The last thing I tried was reinstalling via the website and skipping the set wifi part.
Then the s0*** network appears. 
I chose that network and set the wifi via 192.168.4.1 like you said.
Then the s0 network disappears because it is connected to my home wifi. So I do see my ssid to connect with in the list.

After that, it is connected and is visible again on my network until it starts giving the http_request.arduino:137]
Stream pointer vanished! error. 
This was the case first after a few seconds with the first way. 
And with the skipping the set wifi part, but setting through the 192.168.4.1 after a few minutes.

**Comment by bert1111** [comment]
This is the log after succesfully connecting to my wifi.
And after this it even appears the device crashes after waiting a while. Page does not respond 

`[I][safe_mode:041]: Boot seems successful; resetting boot loop counter
[I][captive_portal:032]: Captive Portal Requested WiFi Settings Change:
[I][captive_portal:033]:   SSID='xxxxxx'
[I][captive_portal:034]:   Password='xxxxxxxx'[redacted]
[W][component:157]: Component wifi set Warning flag: scanning for networks
[I][wifi:540]: - 'xxxxxxx
[I][wifi:313]: WiFi Connecting to 'xxxxx'...
[I][wifi:617]: WiFi Connected!
[W][component:170]: Component wifi cleared Warning flag
[W][component:170]: Component api cleared Warning flag
`

**Comment by huizebruin** [comment]
I will look if i can remove the http sensor for now

**Comment by scns** [comment]
I hope that Will fix the issue.

**Comment by bjornpri** [comment]
Identical problem here on a Wemos D1 Mini V4.0.0 Type-C USB. Has been working fine for a long time. Until 3.6.2: Works after install, stops working with same issue explained in this thred after power recycle.

**Comment by huizebruin** [comment]
i'm pushing now a version online without the ota update and http update .
https://github.com/huizebruin/s0tool/actions/runs/11085402377

**Comment by huizebruin** [comment]
https://github.com/huizebruin/s0tool/actions/runs/11085452651
this looking better

**Comment by huizebruin** [comment]
@bjornpri  and @bert1111 
Would you try it out to flash it from https://s0tool.nl

I uploaded the changes. 

https://github.com/huizebruin/s0tool/actions/runs/11085452651/job/30801987513

**Comment by bjornpri** [comment]
I tried twice. No change. Is there a visual change I can look for so we know I have the new version?

**Comment by huizebruin** [comment]
I named the version inside of the basis file 3.6.3

**Comment by bjornpri** [comment]
Is still says 3.6.2 every where. I tried a third time. No change. After install i visit the device and it loks good. Then without removing power i press the restart link in the web UI and it comes up with the sam issue.

**Comment by scns** [comment]
The release build is not yet started. @huizebruin, van you publish 3.6.3?

**Comment by scns** [comment]
> I named the version inside of the basis file 3.6.3

I think that is not working because The firmware on the website is not updated on The site.

**Comment by huizebruin** [comment]
Its building right now

**Comment by scns** [comment]
Build is done!

**Comment by scns** [comment]
@bjornpri @bert1111 can you try again?

**Comment by huizebruin** [comment]
It should now be online,  i flasht a spare part one now from the website to 3.6.3.

**Comment by bjornpri** [comment]
Almost. It survives all kinds of resets. but... I can not add it to ESP Home:

INFO ESPHome 2024.9.1
INFO Reading configuration /config/esphome/s0tool-watermeter-202f4c.yaml...
INFO Updating https://github.com/huizebruin/s0tool/@main
INFO Detected timezone 'Europe/Oslo'
Failed config

update.http_request: [source /data/packages/b59da29a/esphome/components/s0tool-watermeter-update.yml:2]
  
  Component update.http_request requires 'platform: http_request' in component 'ota'.
  platform: http_request
  name: Firmware Update
  id: update_http_request
  source: https://s0tool.nl/s0tool-watermeter/manifest.json

**Comment by scns** [comment]
> Almost. It survives all kinds of resets. but... I can not add it to ESP Home:
> 
> 
> 
> INFO ESPHome 2024.9.1
> 
> INFO Reading configuration /config/esphome/s0tool-watermeter-202f4c.yaml...
> 
> INFO Updating https://github.com/huizebruin/s0tool/@main
> 
> INFO Detected timezone 'Europe/Oslo'
> 
> Failed config
> 
> 
> 
> update.http_request: [source /data/packages/b59da29a/esphome/components/s0tool-watermeter-update.yml:2]
> 
>   
> 
>   Component update.http_request requires 'platform: http_request' in component 'ota'.
> 
>   platform: http_request
> 
>   name: Firmware Update
> 
>   id: update_http_request
> 
>   source: https://s0tool.nl/s0tool-watermeter/manifest.json

Dus you remove your old entry in esphome?

**Comment by huizebruin** [comment]
im adding it to my beta machine.
![image](https://github.com/user-attachments/assets/43ca4e84-b9f8-4659-9e9b-f239e04b2efc)

**Comment by bjornpri** [comment]
It failed while verifying the yml file with the error:
Component update.http_request requires 'platform: http_request' in component 'ota'.

I added it in ESPHome and I broke it again. 
I'll try once more deleting old stuff and restarting HA.....

It autodiscovers and I can 'adopt' it... I adopt it and I get:


![Skjermbilde_28-9-2024_20833_5tm9f4r0u5o245ga9vsegd5retwbjalo ui nabu casa](https://github.com/user-attachments/assets/7abb7368-55f7-4ee4-b90a-799d324c946d)

**Comment by huizebruin** [comment]
I've been testing it now a couple of times.  But it's working here now good and no losses that the device is going offline.

**Comment by huizebruin** [comment]
Adopt first to ESPHome and after that to Home assistant. 

But did you delete it from your esphome dashboard also?

**Comment by scns** [comment]
I think The repo needs to be refreshed on your'e instance. 

In the worst case you have to wait till tomorrow. (24 hrs)

I had with my own projects The same. 

Sounds weird but sometimes you have to wait. The device in the integration is still working if it has the same name

**Comment by bjornpri** [comment]
> Adopt first to ESPHome and after that to Home assistant.
> 
> But did you delete it from your esphome dashboard also?

That is what I did. Deleted every thing i HA and ESPHome. It fails validating the yaml while adopting in ESPHome. I states it is missing OTA.

**Comment by bjornpri** [comment]
> im adding it to my beta machine. ![image](https://private-user-images.githubusercontent.com/62996429/371780979-43ca4e84-b9f8-4659-9e9b-f239e04b2efc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1NDYwNDYsIm5iZiI6MTcyNzU0NTc0NiwicGF0aCI6Ii82Mjk5NjQyOS8zNzE3ODA5NzktNDNjYTRlODQtYjlmOC00NjU5LTllOWItZjIzOWUwNGIyZWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI4VDE3NDkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0YTY4ZjdlYWI2ZmJkYTk2OTllZTAzYjFhMjAyNjQwNmJiODFhMWFjMDUxMWJhZDYzODM3ZTdlZDE3MzUxMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CycLqUzlImau757iOt-BzzDdv560J4sbmNJJSyv9YrM)

ESPHome 2024.8.1? Im using 2024.9.1.

**Comment by huizebruin** [comment]
![image](https://github.com/user-attachments/assets/2c547ac4-32c0-467b-be7e-331a576c1145)
or try clean build files , then validate , then install

**Comment by bjornpri** [comment]
While selecting "Clean Build Files":

![Skjermbilde_28-9-2024_202720_5tm9f4r0u5o245ga9vsegd5retwbjalo ui nabu casa](https://github.com/user-attachments/assets/ad95dcde-6f5d-419e-85da-eaffee49c157)

**Comment by scns** [comment]
Just wait at least 24 Hours 😅

**Comment by bjornpri** [comment]
It seems that ESPHome 2024.9.1 requires the platform: http_request to be able to properly adopt the device. I can controll it by setting new values and restart it from HA but the enteties in HA will not update. The API wil probably not work without he API encryption key...? Yes?

**Comment by scns** [comment]
I Will test tomorrow.

**Comment by bjornpri** [comment]
> I Will test tomorrow.

Thanks

**Comment by huizebruin** [comment]
Me to and hopefully we find a solution for the problem.

**Comment by scns** [comment]
![image](https://github.com/user-attachments/assets/d18acb03-a115-4d3a-b64a-1e9c457f9745)
![image](https://github.com/user-attachments/assets/f662fb31-1743-4ff1-b0d3-6b9d0edb7596)
![image](https://github.com/user-attachments/assets/e549b293-345f-4259-a7fe-358db4d8d799)
![image](https://github.com/user-attachments/assets/8d709ac9-a507-47ad-8dc1-d2d47bf448c8)

I flashed this morning my production S0 tool. And everyrhing worked fine. 

Import in ESPhome, no problem. And the device came online in HA. I Will monitor of the device stay's online.

**Comment by bjornpri** [comment]
Im testing this morning. Same issue.

![image](https://github.com/user-attachments/assets/a5e4f450-c18e-4841-a3a9-a5e729fe472f)

My tool's yaml file seems to be missing platform: http_request' in component 'ota'.
@scns does your tools yaml file contain the ota component?

![image](https://github.com/user-attachments/assets/609875b1-1ab6-4eac-8daa-f755734962ea)

**Comment by huizebruin** [comment]
@bjornpri  at at line 4 after yaml@main 
maybe is that it.

**Comment by bjornpri** [comment]
@huizebruin What at line 4? Where?
Line 4 in the yaml file there is no ..@main
In the output log there is the timezone on both @scns and mine after ...@main.

**Comment by huizebruin** [comment]
Do you flash it by this link https://s0tool.nl/Installation.html ?
or do you hit the install button inside the esphome dashboard ?

**Comment by JGeeforce** [comment]
Yesterday at 23:23 S0tool was suddenly available. Long story short, this morning I clean build files, deleted the device in ESPhome and did a new install by connecting it to the USB port. It's back again.

**Comment by bjornpri** [comment]
Yes. I use this: 
![image](https://github.com/user-attachments/assets/e7a3382c-3260-4d95-94e3-64fe23c3cdfe)

**Comment by bjornpri** [comment]
> Do you flash it by this link https://s0tool.nl/Installation.html ? or do you hit the install button inside the esphome dashboard ?
> 
> remove the s0tool out of your esphome dashboard and than flash it .

Done this 3 times now. No sucsess

**Comment by huizebruin** [comment]
![image](https://github.com/user-attachments/assets/f14d5c85-ab25-498c-9beb-46eb43c3f3de)
im testing that one at his moment too

**Comment by bjornpri** [comment]
The flash is good. Works fine. Does not breake the device. Stands reboots. All fine so far.

**Comment by bjornpri** [comment]
@huizebruin 
Does your ESPHome yaml file for your device include:

ota:
  - platform: esphome
  - platform: http_request

**Comment by huizebruin** [comment]
![image](https://github.com/user-attachments/assets/eb60876d-9e59-4686-967f-293995f47258)
its adopted here
And still online for 15 min
![{5C638886-049B-4B79-B256-DF77ED27A859}](https://github.com/user-attachments/assets/52690b69-d9f8-4a6e-95e1-ea04ac3234f0)
And now a hard reboot of the device and its come normal online .
![{65590B1D-3F63-48C6-AB70-9E662918B98B}](https://github.com/user-attachments/assets/ae012d2f-20eb-4aa6-b647-427daac5cd25)

**Comment by bjornpri** [comment]
> @huizebruin Does your ESPHome yaml file for your device include:
> 
> ota:
> 
> - platform: esphome
> - platform: http_request

@huizebruin Can you please confirm this?

**Comment by bjornpri** [comment]
My device D1 mini v4 usbc brakes back to the original problem:
![image](https://github.com/user-attachments/assets/eade4d60-9e03-4267-9e54-3fb10199c7c4)

**Comment by huizebruin** [comment]
no i did delete that for now @bjornpri 
its not necessary for esphome to need that.
and there are a lot more people that are having trouble with that at this moment for also other tools.

that's why i push version 3.6.3 online

**Comment by huizebruin** [comment]
https://discord.com/channels/429907082951524364/1283861358483603456

we had the same problem before.
it looks that the package updates once every 24H.
i am looking if i can change that in my esphome config for the s0tool.
can you try it again later today ?

**Comment by bjornpri** [comment]
It sems to work now. But I can not adopt it. If I do it fails as decribed above.
![image](https://github.com/user-attachments/assets/f7b83867-c69c-4234-bcb4-b3184d269271)

**Comment by scns** [comment]
Try the adoption this evening or tomorrow. I think it Will work after Some time.

**Comment by bjornpri** [comment]
> https://discord.com/channels/429907082951524364/1283861358483603456
> 
> we had the same problem before. it looks that the package updates once every 24H. i am looking if i can change that in my esphome config for the s0tool. can you try it again later today ?

I will try in a day or two remotely. My install is at a remote location and im leaving here and will not be back for a couple of weeks, But I will check back.

**Comment by bert1111** [comment]
Hi, I just installed version 3.6.3. No error so far. I noticed that after I set the value of my watermeter again and then unplugged the usb and switched to a usb adapter power source, the value I just set was changed to the initial value of 8m³ again. I set it again and check later if it stays set correctly.

**Comment by JGeeforce** [comment]
> Hi, I just installed version 3.6.3. No error so far. I noticed that after I set the value of my watermeter again and then unplugged the usb and switched to a usb adapter power source, the value I just set was changed to the initial value of 8m³ again. I set it again and check later if it stays set correctly.

Noticed the same behavior here.....

**Comment by bert1111** [comment]
I just restarted HA after an update of something else and the correct value is still being displayed in HA as well as on the page of the watermeter.

**Comment by huizebruin** [comment]
@JGeeforce 
does it work again?

**Comment by JGeeforce** [comment]
> @JGeeforce does it work again?

Well I guess not, I just unplugged the USB, and the watermeterstand changed:

![image](https://github.com/user-attachments/assets/960ecec7-2a16-450f-a9b1-ec6698156044)
