### ISSUE TITLE
Change version type

### ISSUE THREAD

**Issue by huizebruin** [huizebruin/s0tool#63]
Should i change the version from 
V22.11.23 to a other format?

its now 
22 means year
11 means month
23 means total of updates from the beginning.

to a version type like 
v2.6.23

Major -  Ik ga het gebruiken als er een nieuw jaar is, zoals 2022 een 2 zal zijn en 2023 een 3.
.
Minor -  Wordt geüpdatet bij grote wijzigingen
.
Micro -  Wordt geüpdatet bij kleine wijzigingen zoals een fix

Modifier - zoal "dev", "alpha", "beta", "rc1", enz. Wordt alleen gebruikt bij test systemen.

gebaseerd op https://calver.org

**Comment by JGeeforce** [comment]
No, don't. As for me a major update would mean new features etc, Not a new year. Leave it like it is.
