### ISSUE TITLE
Meterstand bijwerken probleem / Update meter reading problem

### ISSUE THREAD

**Issue by huizebruin** [huizebruin/s0tool#64]
Als je de meterstand invult en daarna gaat kijken is hij hoger dan je hebt ingevuld.

Dit komt omdat hij de totaal pulsen erbij op telt.

--------------------------------------

If you fill in the meter reading and then look at it, it is higher than you entered.

This is because he adds the total pulses.

**Comment by ton6i** [comment]
En als je die pulsen eraf trek wanneer bij het schrijven?
            value: !lambda "return ( meter_value - (id(total_water_pulses) * 0.001) ) ;"

**Comment by huizebruin** [comment]
> En als je die pulsen eraf trek bij het schrijven?
>             value: !lambda "return ( meter_value - (id(total_water_pulses) * 0.001) ) ;"
> 

Bedankt voor je antwoord, dat is het.
Komt een dezer dagen online de fix.
