### ISSUE TITLE
Blueprint does not work for watermeter

### ISSUE THREAD

**Issue by balk77** [huizebruin/s0tool#69]
I am using the water-only version of S0 Tool, installed through the button [here](https://huizebruin.github.io/s0tool/). In generates this sensor: `sensor.s0tool_watermeter_versie`

The Blueprint [referenced on this  page](https://github.com/huizebruin/s0tool) compares another sensor:
```
- condition: template
    value_template: |-
      {{
                states('sensor.s0tool_versie_github')
                !=
                states('sensor.s0tool_versie')
              }}
```
Are you able to create a separate blueprint for the watermeter?

**Comment by huizebruin** [comment]
when update v22.11.24 is getting online.
i think with a couple off days.
u can use the old blueprint again.
i changed te name , so i don't need more blueprints.
