### ISSUE TITLE
Pulse Sensor Water OFF

### ISSUE THREAD

**Issue by wes1993** [huizebruin/s0tool#76]
Hello,
thanks a lot for your wonderful project!!!
I have one problem, i have installed the standard version but the Pulse Sensor Water is OFF... how can i turn on?

![image](https://user-images.githubusercontent.com/52070589/202873369-6843ac2c-6f1d-459d-960d-2b04768b930d.png)

I have connected to D5 and the Kw counter works well.

Thanks a lot
Stefano

**Comment by wes1993** [comment]
Solved by removing the resistor from 5V and D2 pin

**Comment by huizebruin** [comment]
it wil switch's off and on when you are using water of use the kwh counter.

**Comment by wes1993** [comment]
Thanks a lot for your reply :-D
