### ISSUE TITLE
Help with Maddalena CD One TRP

### ISSUE THREAD

**Issue by wes1993** [huizebruin/s0tool#77]
Hello, 
i hope someone could help me and this is the correct way to post:

I have the Maddalena CD One TRP water meter and i have bought this sensor from Aliexpress:

https://it.aliexpress.com/item/32582384960.html?spm=a2g0o.new_account_index.0.0.7b6825b9A0W8v0&gatewayAdapt=glo2ita

I have installed and configured everything correctly infact the sensor works well when i try with a magnet but if i put on the water meter won't work... do you have some suggestion on how i can test if my water meter magnet work well?

I have seen form the Maddalena website that my water meter is compatible with this sensor:

https://www.maddalena.it/prodotto/reed-switch-trp-one/#form-product

I hope in you reply
Bye
Stefano

**Comment by HobbitBluelabel** [comment]
Hi Stefano,
Are you sure that 5 mm detection  is enough? 
I need a 8mm sensor on my watermeter to get correct pulses...
Bye,
Jan-Willem

**Comment by wes1993** [comment]
Thanks a lot @HobbitBluelabel for your fast reply :-D
I don't know that there is difference between sensors apart from the voltage...
I think i need a 8mm sensor at this point... there is a way to test the mm?

Bye
Stefano

**Comment by wes1993** [comment]
@HobbitBluelabel 
P.S. can you send me the link of your sensor?

**Comment by HobbitBluelabel** [comment]
Heschen inductieve nabijheidssensor schakelaar LJ18A3-8-Z/AX detector 8 mm
6-36 VDC 300mA NPN normaal gesloten(NC) 3 draad https://amzn.eu/d/bBJkKuf


Op ma 21 nov. 2022 16:13 schreef wes1993 ***@***.***>:

**Comment by huizebruin** [comment]
Npn Sensor [Aliexpres](https://s.click.aliexpress.com/e/_AVaoGr)

that one is 8mm 
M18 8mm sensing DC 5V inductieve proximity sensor switch NPN GEEN LJ18A3-8-Z/BX-5V

**Comment by huizebruin** [comment]
> Hello, i hope someone could help me and this is the correct way to post:
> 
> I have the Maddalena CD One TRP water meter and i have bought this sensor from Aliexpress:
> 
> https://it.aliexpress.com/item/32582384960.html?spm=a2g0o.new_account_index.0.0.7b6825b9A0W8v0&gatewayAdapt=glo2ita
> 
> I have installed and configured everything correctly infact the sensor works well when i try with a magnet but if i put on the water meter won't work... do you have some suggestion on how i can test if my water meter magnet work well?
> 
> I have seen form the Maddalena website that my water meter is compatible with this sensor:
> 
> https://www.maddalena.it/prodotto/reed-switch-trp-one/#form-product
> 
> I hope in you reply Bye Stefano

did u fixed it ?

**Comment by wes1993** [comment]
I have ordered the new sensor from aliexpress, when arrive I will do the test and keep you and the post updated :)

thanks a lot

**Comment by HobbitBluelabel** [comment]
Thanks!
Hartelijke groet,
Jan-Willem van den Hoek


Op wo 30 nov. 2022 om 22:13 schreef wes1993 ***@***.***>:

**Comment by wes1993** [comment]
Hello @HobbitBluelabel,
Today I have received the new sensor, 8mm distance, I have installed everything again but unfortunately this sensor, like the other, won’t work… if I try with piece of iron works well…. So at this point I don’t know what is the best sensor for my meter… probably I need another more performant sensor connect with an optocouper…

Someone have suggestion?

**Comment by huizebruin** [comment]
![5f14fc890a9112c77c28bee3_Dcell + Maddalena + Reed switch.jpg](https://user-images.githubusercontent.com/62996429/206094965-db6f52c5-8ebc-4e33-b033-b0307d548d02.jpg)

I found this picture on Google.
Did you try it in that section?

**Comment by wes1993** [comment]
Yes, I have tried but unfortunately won’t work… I don’t know why… I thin 8mm are not so much…

**Comment by huizebruin** [comment]
> Yes, I have tried but unfortunately won’t work… I don’t know why… I thin 8mm are not so much…

Do u have a picture for me from your meter?
type and with the counters

**Comment by wes1993** [comment]
@huizebruin,
sorry for my very late response.. :-( unfortunately i have read only tosay that you have replied to this...
Here is my meter (Maddalena CD One TRP):
![image](https://user-images.githubusercontent.com/52070589/216391697-a5db0e09-4720-4c79-b7a1-da71c524894c.png)
![image](https://user-images.githubusercontent.com/52070589/216391886-15ddb673-6f50-4cd7-93e5-c6517ca6e45c.png)

Bye
Stefano

**Comment by wes1993** [comment]
Unfortunately for now I can’t find a sensor that works.. I have bought 4mm and 8mm but seems that won’t work… :(

**Comment by wes1993** [comment]
I have found a solution to this (It can be useful also for tracking single device, like washer machine etc.):
I have bought this sensor:
https://www.amazon.it/dp/B08KGG1H8Y?psc=1&ref=ppx_yo2ov_dt_b_product_details

Then i have connected the cable in this way (without Resistor):
Sensor --> ESP
BLK --> GND
RED --> +5V
Yellow --> D2

This configuration works well and i can read correclty the pulses but... the l/min value is not correct... this is what is written in the page:
![image](https://user-images.githubusercontent.com/52070589/216793151-c7957640-b119-40f7-b8bd-c76d393435ca.png)

Can we add a custom value instead of the select menu so we can use custom values to know the l/min?

I have seen in the code that s0tool do this operation for read the l/min:

return x * atof(id(Select_pulse_water).state.c_str()) * 1000

Probably. what i can insert the correct value i can calculate the correct value to insert.

Thanks again a lot for your wonderful work.
Stefano

**Comment by wes1993** [comment]
This is the value that the program read, we know that this is not possible :-D

![image](https://user-images.githubusercontent.com/52070589/216793212-73d20f9c-78c3-4606-97bd-aa2b0825845c.png)

I have only opened a faucet not a hydrant :-D

**Comment by huizebruin** [comment]
do you see the pulsrate water ?
there you can adjust the counting ist normaly 0.001 (1 puls a liter)
if needed i can make it more adjustable

**Comment by wes1993** [comment]
Hello @huizebruin 
I can read the pulses because here it will change ON/OFF state:
![image](https://user-images.githubusercontent.com/52070589/216811567-1b8980bd-ae20-4dd2-83d6-278ff753bf10.png)

But the problem is that from what i have seen in the specs of this sensor 5 pulses is 1 l/min

If you want i can test if you make a new release 

Do you have discord?

Bye 
Stefano

**Comment by wes1993** [comment]
P.S. Hopw did you calculate the l/min ( you do a sum of old value or something else?

**Comment by huizebruin** [comment]
yes i have discord, and have a Dutch server for my work, but have now also a English channel about the s0tool ( and his code) [https://discord.gg/k9cRBSNr](https://discord.gg/k9cRBSNr)

**Comment by So871** [comment]
> @huizebruin,
> sorry for my very late response.. :-( unfortunately i have read only tosay that you have replied to this...
> Here is my meter (Maddalena CD One TRP):
> ![image](https://user-images.githubusercontent.com/52070589/216391697-a5db0e09-4720-4c79-b7a1-da71c524894c.png)
> ![image](https://user-images.githubusercontent.com/52070589/216391886-15ddb673-6f50-4cd7-93e5-c6517ca6e45c.png)
> 
> Bye
> Stefano

It looks like you don't have a metal part on the meter that can be picked up by the NPN sensor.

The npn needs a metal part that triggers it, and judging from your picture it's not there.
So you won't be able to read it with a pulse sensor.
