### ISSUE TITLE
Updated to v22.11.25: Watermeter stand has 4 digits after the comma

### ISSUE THREAD

**Issue by JGeeforce** [huizebruin/s0tool#78]
I just updated to v22.11.25. At first the watermeter stand went to the default value of 8000, which I didn't set. But after changing it via Services the meterstand has 4 digits after the comma, 1989,5350 for example. It should have 3 I guess. 

All values have 4 digits now......
![image](https://user-images.githubusercontent.com/2481255/203856076-51e82df9-bffe-4eac-a45f-9de03534b6a2.png)

**Comment by huizebruin** [comment]
Why the Meter counter is set to 8000 I don't know at this point.

I have nothing set to that number.

And the 4 numbers after the , is because of the meter that's counts every 0.5l

But at this point I don't know how to make a easy switch between 3 and 4 after the comma.

We are working at this.

**Comment by JGeeforce** [comment]
Second time the change went fine. Let's forget the 800 for now.

Thanks for the explanation. Hopefully it will be back to 3 (in my case) soon.

**Comment by huizebruin** [comment]
i am going to push it now to the 3 numbers after the comma.

**Comment by JGeeforce** [comment]
Thanks for the hard work.
