### ISSUE TITLE
yaml errors

### ISSUE THREAD

**Issue by gwittenaar** [huizebruin/s0tool#85]
First of all, very nice project.
But when i tried to adopt the device in esphome it came back with the message: failed config. See attached screen for details.
Probably i do something wrong but i don't what.

![watermeter yaml erros](https://user-images.githubusercontent.com/10408749/207969021-676adf10-ef95-4573-a34d-ad3208a54753.png)

**Comment by huizebruin** [comment]
You must update your esphome to minimal version 2022.11.x

And also have Home Assistant version v2022.11.x minimal.

Than it's must be going to work.

**Comment by gwittenaar** [comment]
Thanks for the fast reaction.
You're right. I was using the version 2022.3.xx but i didn't noticed it was the community version, thats why i never got an update because you have to use the official version. So i installed the official version (2022.12.xx) and it works.
Thanks.
